In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression
from sklearn.neighbors import KNeighborsRegressor


x,y = make_regression(n_samples=1000, n_features=2, noise=3, random_state=1)

In [3]:
x

array([[-0.91542437, -1.94504696],
       [-2.30490794, -0.59246129],
       [-0.43750898, -0.78191168],
       ...,
       [-0.46867382,  0.02186284],
       [-0.44265541,  0.55753264],
       [-0.13971173,  0.85328219]])

In [4]:
y

array([-190.03258306,  -85.26051217,  -79.38260295,  -68.46860406,
          7.6776908 ,  -40.35627711,   37.76165512,  -98.68667297,
       -103.49936616, -111.4844082 ,   74.447244  ,   16.74943836,
       -113.89842347,  127.60069439, -104.93211336,   46.33988172,
         14.22936786,  -67.02417655, -110.81141065, -148.68676949,
          8.82971657,   15.87695178,  -14.63414628,   72.69620209,
        108.28395145,    4.7681583 ,  122.70577279,   26.80503947,
         26.05435416,  -22.0578647 ,   76.52458928, -259.93124079,
         26.45161346,  -43.02760158,   31.73017335,  -41.68557901,
         20.2425586 ,  -38.08420722,  -27.93409336,   94.98962026,
         52.38050255,   94.41735191,   27.21304024,  -40.32774788,
        -42.33719649,   29.52470825,  -25.7761902 ,    8.21058588,
        -64.76327716,  103.57997725,  -95.22499841,  110.24508447,
         30.56383975,   34.43757618, -127.51124629,   73.49122997,
        -29.80642858,  -57.0612244 ,   34.83454862, -174.39757

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [6]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((800, 2), (200, 2), (800,), (200,))

In [8]:
knn=KNeighborsRegressor()
knn.fit(x_train,y_train)

KNeighborsRegressor()

In [9]:
y_pred=knn.predict(x_test)

In [13]:
y_pred.shape

(200,)

In [15]:
#Evaluation

from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error


print(f'r2_score:{r2_score(y_test,y_pred)}')
print(f'mean_absolute_error:{mean_absolute_error(y_test,y_pred)}')

r2_score:0.9882345070834917
mean_absolute_error:5.642182421020689


In [16]:
from sklearn.model_selection import GridSearchCV

params_grid={
    'n_neighbors': [3,5,6,7,9,11,13],
    'weights': ['uniform', 'distance'],
    'algorithm':['auto','ball_tree','kd_tree','brute'],
    'leaf_size': [20,30,40,50]
}

In [17]:
grid = GridSearchCV(estimator=knn, param_grid=params_grid, cv=5)

In [18]:
grid

GridSearchCV(cv=5, estimator=KNeighborsRegressor(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [20, 30, 40, 50],
                         'n_neighbors': [3, 5, 6, 7, 9, 11, 13],
                         'weights': ['uniform', 'distance']})

In [19]:
grid.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsRegressor(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [20, 30, 40, 50],
                         'n_neighbors': [3, 5, 6, 7, 9, 11, 13],
                         'weights': ['uniform', 'distance']})

In [20]:
grid.best_params_

{'algorithm': 'auto', 'leaf_size': 20, 'n_neighbors': 5, 'weights': 'distance'}

In [21]:
grid.best_estimator_

KNeighborsRegressor(leaf_size=20, weights='distance')

In [22]:
grid.best_score_

np.float64(0.9911523277738897)

In [23]:
y_pred_tuned=grid.predict(x_test)

In [24]:
y_pred_tuned

array([ -32.50407668,  -89.46156773,  168.58191231,   22.41137273,
         78.92808532,   21.6520943 ,  -19.23363931,  164.56045796,
       -165.24652395,  105.92376579,   65.52075571,   21.16656286,
        -74.97284521,  103.29403646,   22.78454853, -157.3063811 ,
        162.88042089,   37.52054522,  -17.96061577,  -13.71019775,
       -168.16469337,   15.16385681,   21.11136272,   35.03837567,
         33.55139293,   17.45859585,  -78.4696535 ,  -87.04507115,
        148.41756301,  205.14650328,  201.90721647,   29.63542717,
         97.36632423,   33.03592943,   69.95838813,   31.09080108,
        -80.256027  ,  106.48524208, -181.27213782,  -19.2957041 ,
        143.04048147,  136.10872519,  -46.00359014, -199.11418067,
        -38.46452068,    9.82786029,  -58.51325565,   89.2460245 ,
        -57.56118946,  -48.48710892,   49.15130512,   40.78387837,
          9.11007902,  -38.96929584,   -5.72436045,   -5.47277305,
        133.6599323 ,   57.14533997,  -95.71310516,  132.28093

In [25]:
final_model = grid.best_estimator_
final_model.predict(x_test)

array([ -32.50407668,  -89.46156773,  168.58191231,   22.41137273,
         78.92808532,   21.6520943 ,  -19.23363931,  164.56045796,
       -165.24652395,  105.92376579,   65.52075571,   21.16656286,
        -74.97284521,  103.29403646,   22.78454853, -157.3063811 ,
        162.88042089,   37.52054522,  -17.96061577,  -13.71019775,
       -168.16469337,   15.16385681,   21.11136272,   35.03837567,
         33.55139293,   17.45859585,  -78.4696535 ,  -87.04507115,
        148.41756301,  205.14650328,  201.90721647,   29.63542717,
         97.36632423,   33.03592943,   69.95838813,   31.09080108,
        -80.256027  ,  106.48524208, -181.27213782,  -19.2957041 ,
        143.04048147,  136.10872519,  -46.00359014, -199.11418067,
        -38.46452068,    9.82786029,  -58.51325565,   89.2460245 ,
        -57.56118946,  -48.48710892,   49.15130512,   40.78387837,
          9.11007902,  -38.96929584,   -5.72436045,   -5.47277305,
        133.6599323 ,   57.14533997,  -95.71310516,  132.28093